// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiadkrjqbietlpoilpaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppYWRrcmpxYmlldGxwb2lscGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTEzNTAsImV4cCI6MjA1NDg2NzM1MH0.E0FfCL0MQ3r-1hktIi0r4w_YZXjnw_HE1Z-BTQODL_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);